// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8Kogz7xnv2ZhpaG9RlfW3v8ZHmQED9lk',
    appId: '1:317436756174:android:bf639cc1fea208513b509f',
    messagingSenderId: '317436756174',
    projectId: 'my-halak',
    storageBucket: 'my-halak.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdyeoqXO7IGd-2-RefAOF9699X2izbwMQ',
    appId: '1:317436756174:ios:cfb2d43e78485df03b509f',
    messagingSenderId: '317436756174',
    projectId: 'my-halak',
    storageBucket: 'my-halak.firebasestorage.app',
    iosClientId: '317436756174-i89tre8d4h7nr4rpvm4755cd4gp70agg.apps.googleusercontent.com',
    iosBundleId: 'com.halake.barber.halakeBarber',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE73Kn8ILT4XSQpo7Kb0KtOh0TZ9aULyc',
    appId: '1:317436756174:web:4ccf5effcf7134583b509f',
    messagingSenderId: '317436756174',
    projectId: 'my-halak',
    authDomain: 'my-halak.firebaseapp.com',
    storageBucket: 'my-halak.firebasestorage.app',
    measurementId: 'G-8KX8E7TVN6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdyeoqXO7IGd-2-RefAOF9699X2izbwMQ',
    appId: '1:317436756174:ios:cfb2d43e78485df03b509f',
    messagingSenderId: '317436756174',
    projectId: 'my-halak',
    storageBucket: 'my-halak.firebasestorage.app',
    iosClientId: '317436756174-i89tre8d4h7nr4rpvm4755cd4gp70agg.apps.googleusercontent.com',
    iosBundleId: 'com.halake.barber.halakeBarber',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE73Kn8ILT4XSQpo7Kb0KtOh0TZ9aULyc',
    appId: '1:317436756174:web:a6e8c7b7efd47bf63b509f',
    messagingSenderId: '317436756174',
    projectId: 'my-halak',
    authDomain: 'my-halak.firebaseapp.com',
    storageBucket: 'my-halak.firebasestorage.app',
    measurementId: 'G-MGZ7FP4GJ8',
  );

}